server:
  port: 8080

spring:
  application:
    name: ssolv-api-core
  
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/${DEFAULT_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

# WAS 헬스 체크 및 모니터링 관련
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 0.1
  otlp:
    tracing:
      endpoint: http://alloy:4318/v1/traces
  prometheus:
    metrics:
      export:
        enabled: true

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 43200000   # 12시간
  refresh-token-validity: 604800000   # 1주일

# 앱 설정
app:
  env: local

# 카카오 OAuth 설정
kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: http://localhost:8080/auth/callback
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me

springdoc:
  swagger-ui:
    urls:
      - name: Core API
        url: /v3/api-docs
      - name: Place API
        url: /places/v3/api-docs