server:
  port: 8081

spring:
  application:
    name: ssolv-api-place
  
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/${DEFAULT_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

# 앱 설정
app:
  env: local


api:
  google:
    places:
      api-key: ${GOOGLE_PLACES_API_KEY}
      base-url: https://places.googleapis.com