server:
  port: 8081

spring:
  application:
    name: ssolv-api-place
  
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/${DEFAULT_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

# 앱 설정
app:
  env: local


api:
  google:
    places:
      api-key: ${GOOGLE_PLACES_API_KEY}
      base-url: https://places.googleapis.com
  gemini:
    api-key: ${GEMINI_API_KEY}
    base-url: https://generativelanguage.googleapis.com
    model: gemini-2.5-flash

# WAS 헬스 체크 및 모니터링 관련
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 0.1
  otlp:
    tracing:
      endpoint: ${OTLP_ENDPOINT:http://alloy:4318/v1/traces}
  prometheus:
    metrics:
      export:
        enabled: true